### ISSUE TITLE
Error while building for IOS

### ISSUE THREAD

**Issue by blaZ3** [mconf/bbb-air-client#10]
@fcecagno Hi i am using the mconf bbb-air-client it works well but when i try to build for IOS am getting some errors in the AirCompatability ANE -ios_version_min is undefined

**Error occurred while packaging the application:**

**ld: unknown option: -ios_version_min
Compilation failed while executing : ld64**

**Comment by LucasMFreire** [comment]
Hi @blaZ3 

I´ve never seen this error before. Some references I could find are [this](http://www.richardlord.net/blog/20-tips-for-creating-air-native-extensions-for-ios) (see number 18) and [this](http://juankpro.com/wordpress/2012/05/10/local-notification-ane-source-code/) (see comments section).

Apparently it could be a problem with your sdk version. Which flex sdk version are you using?

Are you compiling on a Mac? Can you build it for the iOS emulator?

**Comment by cherishsantosh** [comment]
Hey @LucasMFreire I am also facing same problem, I am using Windows 7, building for iOS. My flex SDK Version is 4.6, any solution for this.

**Comment by fcecagno** [comment]
@cherishsantosh Have you tried to look at the references @LucasMFreire suggested in the previous comment?

@blaZ3 Were you able to fix the issue? Could you please share your findings?

**Comment by blaZ3** [comment]
@fcecagno no I was not able to fix the issue. I am trying to build on a MAC. I tried to build via CLI with the -platformsdk flag also, but am getting the same error.

**Comment by blaZ3** [comment]
@fcecagno Fixed the issue, I was using the wrong version of adt to build and also had to remove the -platformsdk flag while building from CLI
