### ISSUE TITLE
Configure the app name and icon

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bbb-air-client#19]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1119, http://dev.mconf.org/redmine/issues/1119
Original Date: 2014-01-09

---

Today we're using default data for the app name and icon - we should use the Mconf information and be prepared to change in a branch to BigBlueButton information.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Herbert Jones** (Lucas Herbert Jones)
Original Date: 2014-01-22T16:52:00Z

---

Icon and name added to the app.

**Comment by daronco** [comment]
---

Original attachments:
* [mconf_logotipoballoon](https://cloud.githubusercontent.com/assets/498566/15031278/d6a97772-122d-11e6-96c7-6231790bbac3.png)
* [mconf_logotipoballoon_wb](https://cloud.githubusercontent.com/assets/498566/15031279/d6d25246-122d-11e6-98f9-fc113594446f.png)
* [mconf_logotipopadrao](https://cloud.githubusercontent.com/assets/498566/15031280/d6d44b8c-122d-11e6-8258-0323c7bc45f9.png)

---
