### ISSUE TITLE
Message and username is getting overlapped in the public chat

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bbb-air-client#22]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1122, http://dev.mconf.org/redmine/issues/1122
Original Date: 2014-01-09

---

See the screenshot attached.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Lucas Herbert Jones** (Lucas Herbert Jones)
Original Date: 2014-01-13T06:30:03Z

---

Removi a inteligencia de só postar nome de usuario diferente do anterior e data diferente da anterior.

**Comment by daronco** [comment]
---

Original attachments:
* [screenshot 01_46pm jan 09 2014](https://cloud.githubusercontent.com/assets/498566/15031256/b2f80546-122d-11e6-8524-01b121c12bae.png)

---
