### ISSUE TITLE
Use the new icons

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bbb-air-client#26]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1132, http://dev.mconf.org/redmine/issues/1132
Original Date: 2014-01-20

---

This is low priority right now.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Date: 2015-02-13T18:54:54Z

---

Old issue, create a new one if needed.

**Comment by daronco** [comment]
---

Original attachments:
* [bbb-mobile-icons.zip](https://github.com/mconf/bbb-air-client/files/249690/bbb-mobile-icons.zip)

---
