### ISSUE TITLE
bbb-air-client video and audio not working in android device

### ISSUE THREAD

**Issue by days4** [mconf/bbb-air-client#7]
Hello, I am creating an app using bbb-air-client to attend a session.I am able to join the meeting and getting the slides properly. But the problem is ,i am not able to get the audio and video in my app.Also when i change the meeting mode(listen only etc.) the connection drops. When i open camera in my mobile then a frame appears on presenter side but video is not displayed. Similarly when webcam is open at presenter then presenter name and camera icon is visible in the app not actual video. Please help to resolve this problem.
i am using adobe air ver 18 and android ver 5 (lollipop). and handsets to test are lenovo a7000, Karbonn A9+
Thanks

**Comment by fcecagno** [comment]
Hi @days4,
What's the version of your BigBlueButton server, and what's the revision you're using on bbb-air-client? Is it plain bbb-air-client or did you do any development on top of it?
Is your BigBlueButton server fully functional when you access via web browser?

**Comment by days4** [comment]
hi @fcecagno ,
thanks for your reply .The version of my BigBlueButton server is 0.9.0 and i am using bbb-air-client master provided at bigbluebutton/bbb-air-client .yes its plain bbb-air-client all that i had changed is the join url .and my bigbluebutton server is fully functional when i access it via web browser.Is there  any configuration i have to make at bigbluebutton server side.

**Comment by fcecagno** [comment]
Could you try the branch bbb-compatibility on mconf/bbb-air-client?

**Comment by days4** [comment]
i tried that first but got error saying below
```
at org.bigbluebutton.core::EnterService/onSuccess()[H:\bbb-air-client-master\bbb-air-client\src\org\bigbluebutton\core\EnterService.as:40]
	at org.osflash.signals::Slot/execute()[C:\development\libs\as3-signals\src\org\osflash\signals\Slot.as:100]
	at org.osflash.signals::OnceSignal/dispatch()[C:\development\libs\as3-signals\src\org\osflash\signals\OnceSignal.as:132]
	at org.bigbluebutton.core.util::URLFetcher/handleComplete()[H:\bbb-air-client-master\bbb-air-client\src\org\bigbluebutton\core\util\URLFetcher.as:60]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at flash.net::URLLoader/onComplete()
```
So i moved to bigbluebutton/bbb-air-client and it was working for all features except above

**Comment by fcecagno** [comment]
Here: https://github.com/mconf/bbb-air-client/tree/bbb-compatibility

**Comment by days4** [comment]
thanks @fcecagno  for your help now app is working fine.

**Comment by blaZ3** [comment]
Hi i am using the mconf bbb-air-client it works well but when i try to build for IOS am getting some errors in the AirCompatability ANE -ios_version_min is undefined
