### ISSUE TITLE
Rotated camera

### ISSUE THREAD

**Issue by hipoloco** [mconf/bbb-air-client#8]
On mconf-mobile-0.6, when it's used on a smartphone and the camera is activated, the image is rotated 90 degrees left.

![screenshot_2015-07-02-14-12-53](https://cloud.githubusercontent.com/assets/8184347/8483187/67b84cda-20c5-11e5-867b-64537988c7c2.png)
![screenshot_2015-07-02-14-14-33](https://cloud.githubusercontent.com/assets/8184347/8483188/67bb9642-20c5-11e5-9b5e-acdcead4ec7f.png)

**Comment by bhargavms** [comment]
How do you actually fix this??

**Comment by fcecagno** [comment]
Yes, the camera rotation is done by Mconf-Live, so if it's properly configured, it should rotate the camera according the configuration you set in the app.

**Comment by bhargavms** [comment]
Have a look at this thread, https://forums.adobe.com/thread/842765, it seems this is a bug in the AIR sdk's camera api.

**Comment by fcecagno** [comment]
This is not a preview, this is the actual stream fetched from the server. Did you try to watch the same stream in the web client?
In order to use the camera rotation feature on Mconf-Mobile, you need to use Mconf-Live in the backend, because this is a server-side feature.

**Comment by bhargavms** [comment]
Yes, I'm not talking about the stream from the server, the problem is the video stream that is being sent from the device is rotated by 90 degrees because AIR apparently only records in landscape aspect ratio (i.e width greater than height). So the raw camera captures frames and flips it..

**Comment by fcecagno** [comment]
I understand that, this is a limitation on AIR that can only stream the camera rotated by 90 degrees. This is why we implemented a server-side component that rotates back the stream to the correct position.

**Comment by bhargavms** [comment]
ah, I did NOT know about that ! Thanks for that piece of information.

**Comment by fcecagno** [comment]
You're welcome!
