### ISSUE TITLE
audio & video doesnt work on marshmallow android devices

### ISSUE THREAD

**Issue by human-bieng** [mconf/bbb-air-client#84]
**Hello
i have installed both mconf-web & mconf-live each on its own dedicated server
mobile developer downloaded bbb-air from
https://github.com/mconf/bbb-air-client
the developer build & customized an ios & android apps that will connect to mconf-web which will redirect them to mconf-live server
we can join rooms successfully but we cannot share either microphone or camera within android devices
the test have been done on two android devices that uses marshmallow v6
i have reviewed both servers log & found nothing 
also asked mobile developer but he dont know what is the problem root cause
any help will be appreciated
additional informations 
Mconf-Web latest version 
please all accept our best regards**

**Comment by human-bieng** [comment]
**Hello 
After more than 5 hours of investigation, we realized that the problem was because of Android 6 & 7 permissions
The mconf-mobile app has the code embedded that will automatically set permissions (camera, mic, etc)
While bbb-air-client doesnt have the code embedded within it, so you will have to enable permissions manually 
Are there anyway to have & add this code within bbb-air-client code directly 
I really love & encourage Mconf webconference project 
Please  accept my best regards**

**Comment by fcecagno** [comment]
It looks like the issue doesn't affect master.
