### ISSUE TITLE
IOS packaging error

### ISSUE THREAD

**Issue by blaZ3** [mconf/bbb-air-client#9]
When I try to run the app in iPhone I am getting the following error. I`ve added development certificates and device provisioning certificates already.

**Error occurred while packaging the application:**

**ld: framework not found Twitter
Compilation failed while executing : ld64**

**Comment by fcecagno** [comment]
Can you let us know what was wrong, @blaZ3?

**Comment by blaZ3** [comment]
@fcecagno I am trying to build the project for IOS app via command line using the -platformsdk flag as per this [link](http://blogs.adobe.com/rajorshi/2011/11/16/ios5-support-for-airusing-external-sdks-to-package-apps/) but am getting the error that Twitter and MessageUI framework is not found (The AirCapabilities.ane used in the project refers to these framework). 

I have checked the iPhone sdk framework folder and the MessageUI and Twitter framework exists there.

**Comment by blaZ3** [comment]
@fcecagno Fixed the issue, I was using the wrong version of adt to build and also had to remove the -platformsdk flag while building from CLI

**Comment by fcecagno** [comment]
@blaZ3 What version of adt are you using now? (just to keep it documented here at the issue)

**Comment by bhargavms** [comment]
We're using the AIR sdk thats downloaded from here currently http://www.adobe.com/devnet/air/air-sdk-download.html The version number given there is 21.0

**Comment by fcecagno** [comment]
Nice, thanks for your feedback!
